# backend/core/event_types.py

class EventTypes:
    # Ingestion layer
    WEATHER_UPDATE = "WEATHER_UPDATE"
    SATELLITE_UPDATE = "SATELLITE_UPDATE"
    SOCIAL_REPORT_RECEIVED = "SOCIAL_REPORT_RECEIVED"
    VOLUNTEER_UPDATE = "VOLUNTEER_UPDATE"

    # Detection layer
    FLOOD_CONFIRMED = "FLOOD_CONFIRMED"
    FLOOD_UPDATED = "FLOOD_UPDATED"

    # Intelligence layer
    CLUSTERS_UPDATED = "CLUSTERS_UPDATED"
    RESOURCES_UPDATED = "RESOURCES_UPDATED"
    ROUTES_UPDATED = "ROUTES_UPDATED"

    # Mission lifecycle
    MISSION_REQUESTED = "MISSION_REQUESTED"
    MISSION_CREATED = "MISSION_CREATED"
    MISSION_ASSIGNED = "MISSION_ASSIGNED"
    MISSION_STATUS_UPDATED = "MISSION_STATUS_UPDATED"

    # Notifications
    NOTIFICATION_SENT = "NOTIFICATION_SENT"

    # System
    INCIDENT_STARTED = "INCIDENT_STARTED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"

    VOLUNTEER_REPORT_RECEIVED = "VOLUNTEER_REPORT_RECEIVED"
    MISSION_FAILED = "MISSION_FAILED"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    MISSION_EN_ROUTE = "MISSION_EN_ROUTE"
    MISSION_ACTIVE = "MISSION_ACTIVE"
    FLOOD_INTELLIGENCE_UPDATED = "FLOOD_INTELLIGENCE_UPDATED"